repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
